apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: service-scale-down-job
spec:
  schedule: "0 22 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: service-scheduled-job
              image: service-scheduled-job:latest
              args:
                - "kubectl patch hpa service-hpa --patch '{\"spec\":{\"minReplicas\":3}}'"
              env:
                - name: "SERVICE_ACCOUNT_KEY"
                  valueFrom:
                    secretKeyRef:
                      key: "SERVICE_ACCOUNT_KEY"
                      name: "scale-job-secret"