apiVersion: v1
kind: Service
metadata:
  name: notifications-loadbalancer
spec:
  selector:
    app: notifications
  ports:
    - name: notifications
      port: 8094
      targetPort: 8094
  type: LoadBalancer