apiVersion: v1
kind: Service
metadata:
  name: file-management-loadbalancer
spec:
  selector:
    app: file-management-loadbalancer
  ports:
    - name: http
      port: 8081
      targetPort: 2090
  type: LoadBalancer