apiVersion: v1
kind: Service
metadata:
  name: file-management-loadbalancer
spec:
  selector:
    app: file-management
  ports:
    - name: file-management
      port: 8097
      targetPort: 8097
  type: LoadBalancer