apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: file-management
  template:
    metadata:
      labels:
        app: file-management
    spec:
      containers:
        - name: file-management
          image: matthew9164/filemanagement:latest
          ports:
            - containerPort: 2090
