apiVersion: v1
kind: Service
metadata:
  name: file-metadata-loadbalancer
spec:
  selector:
    app: file-metadata
  ports:
    - name: file-metadata
      port: 8092
      targetPort: 8092
  type: LoadBalancer