# Deploys a new Namespace for the MinIO Pod
apiVersion: v1
kind: Namespace
metadata:
  name: minio-dev # Change this value if you want a different namespace name
  labels:
    name: minio-dev # Change this value to match metadata.name
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
data:
  access.key: ZGVmYXVsdF91c2VyX1hrZTE3dE1QbEo4cmg1NHNPWnk=
  secret.key: M3lyckNsRDBBWHRnN3QxSUdMdmpPdWIxZHN5NV90MEQ=
