apiVersion: v1
kind: Service
metadata:
  name: user-management-loadbalancer
spec:
  selector:
    app: user-management-loadbalancer
  ports:
    - name: http
      port: 80
      targetPort: 2080
  type: LoadBalancer